### ISSUE TITLE
Crash in Reaper 6.42 on Win 10

### ISSUE THREAD

**Issue by crenshawda** [suzumushi0/SoundObject_binary#1]
When I try and add the Sound Object vst to a track in Reaper (6.42) Windows 10 v10.0.19042 Build 19042 the application thinks for a second and then quits with no messages.

Below are the logs I got:

---

Faulting application name: reaper.exe, version: 6.4.2.0, time stamp: 0x619443cb
Faulting module name: SoundObject.vst3, version: 1.0.0.1, time stamp: 0x61937dd1
Exception code: 0xc000041d
Fault offset: 0x00000000001151fd
Faulting process id: 0x5d8c
Faulting application start time: 0x01d7e14f065187a6
Faulting application path: C:\Users\crens\Icedrive\Audio\Reaper\reaper.exe
Faulting module path: C:\Users\crens\Icedrive\Audio\_plugins\VST3\SoundObject\1.4.0\SoundObject.vst3
Report Id: 8aaa5672-13b6-4659-a585-a489c0196cfa
Faulting package full name: 
Faulting package-relative application ID: 

---

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-11-24T23:19:25.5022236Z" /> 
  <EventRecordID>34881</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Raphtalia</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>reaper.exe</Data> 
  <Data>6.4.2.0</Data> 
  <Data>619443cb</Data> 
  <Data>SoundObject.vst3</Data> 
  <Data>1.0.0.1</Data> 
  <Data>61937dd1</Data> 
  <Data>c000041d</Data> 
  <Data>00000000001151fd</Data> 
  <Data>5d8c</Data> 
  <Data>01d7e14f065187a6</Data> 
  <Data>C:\Users\crens\Icedrive\Audio\Reaper\reaper.exe</Data> 
  <Data>C:\Users\crens\Icedrive\Audio\_plugins\VST3\SoundObject\1.4.0\SoundObject.vst3</Data> 
  <Data>8aaa5672-13b6-4659-a585-a489c0196cfa</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by suzumushi0** [comment]
Thank you very much for your feedback.

"SoundObject.vst3" to be installed is a FOLDER in the unzipped file.
It is NOT "SoundObject.vst3\Contents\x86_64-win\SoundObject.vst3".

INSTALL is updated to avoid misleading.
