### ISSUE TITLE
Choppy automation on Cakewalk DAW

### ISSUE THREAD

**Issue by Hinge45** [suzumushi0/SoundObject_binary#4]

**Comment by suzumushi0** [comment]
Could you explain the detailed situation？

**Comment by Hinge45** [comment]
the plugin keeps snapping back and flick
Here's a video example of it.
https://youtu.be/DPUU5E1JVMY

**Comment by suzumushi0** [comment]
(1) The position of the acoustic source is constrained by the inside of the reverberation room. If an outside position is specified by xy-pad, yz-pad, or parameter automation, it is automatically adjusted to an inside position like your video. 
(2) It seems to me, in your video, the size of the reverberation room is not correctly displayed. If you encounter this situation, please try to off and on the bypass switch.
